### ISSUE TITLE
Spark scheduler should keep the pods and resource reservation mapping uptodate

### ISSUE THREAD

**Issue by ashrayjain** [palantir/k8s-spark-scheduler#27]
When pods die/exit, currently the associated resource reservations stay assigned to the pod. It is more desirable to make the spark scheduler behave like a controller and unassign the resource reservation in these cases so that other consumers of resource reservations still get a consistent view of the world.

**Comment by ashrayjain** [comment]
CC @onursatici

**Comment by onursatici** [comment]
As this change requires the extender to have a controller, I believe it is meaningful to do when switching the extender to be a scheduler plugin, which we can do when the scheduling framework lands on 1.15 https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20180409-scheduling-framework.md
