### ISSUE TITLE
Goland project generated by `./godelw goland` does not compile

### ISSUE THREAD

**Issue by uschi2000** [palantir/k8s-spark-scheduler#29]
![Screen Shot 2019-05-07 at 10 15 56 AM](https://user-images.githubusercontent.com/6528449/57284296-2d1e6600-70b1-11e9-90a5-d4990a951356.png)

**Comment by onursatici** [comment]
This happens mostly on wrong clone paths, it should be strictly `$GOPATH/src/github.com/palantir/k8s-spark-scheduler`

**Comment by uschi2000** [comment]
You’re right, my bad. Thanks!
