### ISSUE TITLE
Example in examples/extender.yml bug

### ISSUE THREAD

**Issue by hmike96** [palantir/k8s-spark-scheduler#84]
The example did not work for me on first try because the spark service account searched for in the ClusterRoleBinding is in the default namespace but we create it in the spark namespace, so the scheduler service account assumed lacked the required role of cluster-admin. So the deployment would fail every time because the service account lacked permissions needed. I would do a pull request and change the example but wanted to see if you believed I was missing something. The example works for me now that I have changed the service accounts namespace in the ClusterRoleBinding to spark. Other than that the example works great, thank you for the great tool.

**Comment by onursatici** [comment]
hello @hmike96 thanks for the feedback! Yes I believe this was something we have missed, should be addressed here https://github.com/palantir/k8s-spark-scheduler/pull/85

**Comment by onursatici** [comment]
fixed by https://github.com/palantir/k8s-spark-scheduler/pull/85
