### ISSUE TITLE
[METRICS] - No information on the README.md about a basic metric client setup

### ISSUE THREAD

**Issue by cosmin-ionita** [palantir/k8s-spark-scheduler#86]
Hello, guys!

I'm going through this code and even a non-Go guy like me can quickly realise how well-crafted it is! Great work!

I've been able to run the extender in minikube pretty easily using the instructions provided in the readme, but I'd like to see more insights about how the extender performs. I see that there is already a `/metrics` directory in the project where a lot of metrics seem to be incremented, but I'm still having a hard time trying to understand how can I get those metrics out of the pod, to be able to see them in a dashboard.

I tracked down the dependencies and I found that you guys built a [new library](https://github.com/palantir/pkg/tree/master/metrics) on top [go-metrics](https://github.com/rcrowley/go-metrics), so by reading the readme of that repo I find that I need to set up a client that would expose those metrics to the desired metric engine. But I see that this client takes a metric Registry and exposes it and I'm not really able to figure out where in the code is that Registry that needs to be exposed.

I understand that the metrics setup were probably left undocumented because they use `go-metrics` which I suppose that it's a metric standard in Go-world, or it may be considered as `out-of-scope` for this project, but I really think it would be helpful to include at least a minimal metric setup (with Prometheus, for example). I'd be happy to open a PR with this setup once I'll figure it out.

What do you think?

Thanks,
Cosmin

**Comment by onursatici** [comment]
Hello @cosmin-ionita thanks for the feedback! We use `witchcraft-go` and the way metrics are emitted by default is via a [logger](https://github.com/palantir/witchcraft-go-server/blob/develop/witchcraft/server_metrics.go). All logs from `spark-scheduler-extender` container in the [example](https://github.com/palantir/k8s-spark-scheduler/blob/master/examples/extender.yml#L109) are structured, and in json format. Metric logs have `metric.1` in their `type` field.

As `witchcraft-go` is built for an architecture with a [logging agent](https://kubernetes.io/docs/concepts/cluster-administration/logging/#using-a-node-logging-agent) present, I would prefer to ship metrics to prometheus using such agent, by parsing the metric logs. This way `k8s-spark-scheduler` can be agnostic of what metrics collector is used.

**Comment by cosmin-ionita** [comment]
Hey, @onursatici! Thanks for your answer and for the explanations! I'll try to set up a prometheus agent and see how it goes.

**Comment by cosmin-ionita** [comment]
@onursatici: Could you please tell me what metric agent you're using? I found out that [grok-exporter](https://github.com/fstab/grok_exporter) seems to be the tool. It's able to parse the log metrics and also to export them to Prometheus but it doesn't support all metric types that the extender exports (for example `timer` is not supported). Thanks!

**Comment by onursatici** [comment]
We use an in house built metrics aggregator. I think you would need to set up your agent to be a daemon set and has a mount for the directory that has all container logs in each node, per described (not in great detail though) in [K8S docs](https://kubernetes.io/docs/concepts/cluster-administration/logging/#using-a-node-logging-agent)
